# Generated by Django 5.2.17 on 2026-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoodlePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('creatures', 'Weird Creatures & Pets 🐾'), ('space', 'Cosmic Doodles 🚀'), ('everyday', 'Everyday Objects with Faces ☕'), ('fantasy', 'Tiny Adventures 🍄'), ('abstract', 'Wobbly Feelings & Scribbles 🌀')], default='creatures', max_length=60)),
                ('difficulty', models.CharField(choices=[('quick', '2-Minute Warmup ⏱️'), ('playful', 'Playful Sketch 🎨'), ('wild', 'Wild Imagination 🌟')], default='playful', max_length=30)),
                ('times_drawn', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doodle Prompt',
                'verbose_name_plural': 'Doodle Prompts',
                'ordering': ['-id'],
            },
        ),
    ]
