# Generated by Django 5.2.17 on 2026-09-11 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Short handwritten excerpt for previews', max_length=350)),
                ('body', models.TextField(help_text='Diary entry body (HTML/rich text formatted)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('svg_cover', models.TextField(blank=True, help_text='Inline SVG cover doodle if no raster image')),
                ('mood', models.CharField(default='Crayon Fueled 🖍️', help_text='Author doodle mood', max_length=60)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('read_time', models.CharField(default='3 min doodle read', max_length=40)),
            ],
            options={
                'verbose_name': 'Journal Post',
                'verbose_name_plural': 'Journal Posts',
                'ordering': ['-published_date', '-id'],
            },
        ),
    ]
