# Generated by Django 5.2.17 on 2026-09-11 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doodles/')),
                ('svg_content', models.TextField(blank=True, help_text='Inline SVG doodle illustration code if no raster image provided')),
                ('caption', models.CharField(help_text='Short handwritten-style caption', max_length=300)),
                ('character_tag', models.CharField(choices=[('barnaby', 'Barnaby the Blob'), ('pip', 'Pip the Pencil Bird'), ('cloudia', 'Sir Reginald Cloud'), ('inky', 'Inky the Octopus'), ('cosmic', 'Cosmic Scribble'), ('daily', 'Daily Sketchbook')], default='barnaby', max_length=50)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('tilt_deg', models.IntegerField(default=0, help_text='Subtle scrapbook tilt in degrees (-6 to +6)')),
            ],
            options={
                'verbose_name': 'Doodle Entry',
                'verbose_name_plural': 'Doodle Entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
