# Generated by Django 5.2.17 on 2026-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='footer', max_length=50)),
            ],
            options={
                'verbose_name': 'Doodle Drop Subscriber',
                'verbose_name_plural': 'Doodle Drop Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
