# Generated by Django 5.2.17 on 2026-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your nickname or doodle pen-name', max_length=80)),
                ('message', models.TextField(help_text='A friendly message or doodle thought', max_length=500)),
                ('mood', models.CharField(choices=[('star', '🌟 Starry Eyed'), ('blob', '🧸 Cozy Blob'), ('coffee', '☕ Over-Caffeinated Scribbler'), ('rainbow', '🌈 Pure Joy'), ('crayon', '🖍️ Drawing Wildly'), ('sleepy', '💤 Sleepy Doodler')], default='star', max_length=50)),
                ('paper_color', models.CharField(choices=[('yellow', 'Sunshine Note'), ('coral', 'Coral Note'), ('blue', 'Sky Note'), ('green', 'Grass Note'), ('purple', 'Lavender Note')], default='yellow', max_length=20)),
                ('tilt_deg', models.IntegerField(default=-2, help_text='Scrapbook sticky note tilt')),
                ('is_approved', models.BooleanField(default=False, help_text='Requires admin approval to appear on the public wall')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guestbook Sticky Note',
                'verbose_name_plural': 'Guestbook Sticky Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
